--MEMBER---------
DROP TABLE MEMBER
SELECT * FROM MEMBER

INSERT INTO MEMBER (M_ID, M_PW,M_NAME,M_EMAIL,M_AUTH,M_PHOTO)
VALUES ('bombom','1234','Bom','b@b.b',3,'none');
INSERT INTO MEMBER (M_ID, M_PW,M_NAME,M_EMAIL,M_AUTH,M_PHOTO)
VALUES ('hong','1234','hongma','h@h.h',3,'none');

UPDATE MEMBER SET M_PW='7', M_EMAIL='7' WHERE M_ID='bombom'

DELETE FROM MEMBER WHERE M_ID='qwer'

--MOVIE---------
DROP TABLE MOVIE
CASCADE CONSTRAINT;

DROP SEQUENCE MV_SEQ; 

delete from movie;

SELECT * FROM MOVIE

CREATE TABLE MOVIE(
	MV_SEQ NUMBER PRIMARY KEY,
	MV_TITLE VARCHAR2(200) NOT NULL,
	MV_OPENDAY DATE NOT NULL,
	MV_GENRE VARCHAR2(50) NOT NULL,
	MV_STORY VARCHAR2(2000) NOT NULL,
	MV_IMG VARCHAR2(500) NOT NULL,
	MV_COUNT NUMBER NOT NULL,	
	MV_LIKE NUMBER NOT NULL,
	MV_HATE NUMBER NOT NULL,
	MV_ON NUMBER NOT NULL
)

CREATE SEQUENCE MV_SEQ
START WITH 1 INCREMENT BY 1

--INSERT INTO MOVIE (MV_SEQ, MV_TITLE, MV_OPENDAY,MV_GENRE, MV_STORY, MV_IMG, MV_COUNT, MV_LIKE, MV_HATE, MV_ON )
--VALUES (MV_SEQ.NEXTVAL, '부산행', SYSDATE, '액션/스릴러', '부산행 KTX 안, 좀비VS사람의 생존 싸움', '../img/p_tobusanline.jpg',0,0,0,1);

INSERT INTO MOVIE
VALUES(MV_SEQ.NEXTVAL, '부산행', '20160720', '액션', '정체불명의 바이러스가 전국으로 확산되고 대한민국 긴급재난경보령이 선포된 가운데,열차에 몸을 실은 사람들은 단 하나의 안전한 도시 부산까지 살아가기 위한 치열한 사투를 벌이게 된다.'
, 'http://img.cgv.co.kr/Movie/Thumbnail/Poster/000078/78982/78982_185.jpg', 0, 0, 0, 1)


INSERT INTO MOVIE
VALUES(MV_SEQ.NEXTVAL, '제이슨본', '20160727', '액션,스릴러', '모든 자취를 숨기고 사라졌던 제이슨 본, 그는 되찾은 기억 외에 과거를 둘러싼 또 다른 음모가 있다는 것을 알게 되고 마침내 CIA 앞에 자신의 존재를 드러내게 되는데… 가장 완벽하고 가장 치명적인 무기 ‘제이슨 본’ 이제 모든 것이 그에게 달렸다'
,'http://img.cgv.co.kr/Movie/Thumbnail/Poster/000078/78981/78981_185.jpg', 0, 0, 0, 1)


INSERT INTO MOVIE
VALUES(MV_SEQ.NEXTVAL, '인천상륙작전', '20160727', '드라마, 전쟁', '1950년 6월 25일 북한의 기습 남침으로 불과 사흘 만에 서울 함락, 한 달 만에 낙동강 지역을 제외한 한반도 전 지역을 빼앗기게 된 대한민국. 국제연합군 최고사령관 더글라스 맥아더(리암 니슨)는 모두의 반대 속 인천상륙작전을 계획한다. 성공확률 5000:1, 불가능에 가까운 작전. 이를 가능케 하는 것은 단 하나, 인천으로 가는 길이 확보되어야 하는 것뿐이다. 맥아더의 지시로 대북 첩보작전 X-RAY에 투입된 해군 첩보부대 대위 장학수(이정재)는 북한군으로 위장 잠입해 인천 내 동태를 살피며 정보를 수집하기 시작한다. 하지만 인천 방어사령관 림계진(이범수)에 의해 정체가 발각되는 위기에 놓인 가운데 장학수와 그의 부대원들은 전세를 바꿀 단 한번의 기회, 단 하루의 작전을 위해 인천상륙 함대를 유도하는 위험천만한 임무에 나서는데... 역사를 바꾼 비밀 연합작전 그 시작은 바로 그들이었다! '
, 'http://img.cgv.co.kr/Movie/Thumbnail/Poster/000078/78994/78994_185.jpg', 0, 0, 0, 1)

INSERT INTO MOVIE
VALUES(MV_SEQ.NEXTVAL, '도리를찾아서', '20160706', '애니메이션, 어드벤처, 코미디, 가족', '무엇을 상상하든 그 이상을 까먹는 ‘도리’의 어드벤쳐가 시작된다! 니모를 함께 찾으면서 베스트 프렌드가 된 도리와 말린은 우여곡절 끝에 다시 고향으로 돌아가 평화로운 일상을 보내고 있다. 모태 건망증 도리가 ‘기억’이라는 것을 하기 전까지! 도리는 깊은 기억 속에 숨어 있던 가족의 존재를 떠올리고 니모와 말린과 함께 가족을 찾아 대책 없는 어드벤쳐를 떠나게 되는데…깊은 바다도 막을 수 없는 스펙터클한 어드벤쳐가 펼쳐진다! 
', 'http://img.cgv.co.kr/Movie/Thumbnail/Poster/000078/78907/78907_185.jpg', 0, 0, 0, 1)

INSERT INTO MOVIE
VALUES (MV_SEQ.NEXTVAL, '어바웃타임', '20131205', '멜로/로맨스/코미디', '과거 시간 여행을 할 수 있는 남자와 평범한 여자의 예쁜 로맨스', '../img/p_abouttime.png',0,0,0,0);



--THEATER---------
DROP TABLE THEATER
CASCADE CONSTRAINT;

DROP SEQUENCE TH_SEQ; 

SELECT * FROM THEATER

CREATE TABLE THEATER(
	TH_SEQ NUMBER PRIMARY KEY,
	TH_NAME VARCHAR2(100) NOT NULL,
	MV_SEQ NUMBER NOT NULL, 
	TH_CINEMA VARCHAR2(500) NOT NULL,
	TH_NUM NUMBER NOT NULL,
	TH_TOTALSEAT NUMBER NOT NULL,
	TH_LEFTSEAT NUMBER NOT NULL,
	TH_TIME DATE NOT NULL
)

CREATE SEQUENCE TH_SEQ
START WITH 1 INCREMENT BY 1


SELECT * FROM THEATER

--timestamp
INSERT INTO THEATER
VALUES(TH_SEQ.NEXTVAL, '명동', 1, '1관', 1, 10, 10, to_date('16-07-29 12:30:00','YY-MM-DD HH24:MI:SS'))

INSERT INTO THEATER
VALUES(TH_SEQ.NEXTVAL, '명동', 1, '1관', 2, 10, 10, to_date('16-07-29 3:00:00','YY-MM-DD HH24:MI:SS'))

INSERT INTO THEATER
VALUES(TH_SEQ.NEXTVAL, '명동', 1, '3관', 1, 10, 10, to_date('16-07-29 17:30:00','YY-MM-DD HH24:MI:SS'))


INSERT INTO THEATER
VALUES(TH_SEQ.NEXTVAL, '명동', 2, '2관', 1, 10, 10, to_date('16-07-29 13:00:00','YY-MM-DD HH24:MI:SS'))

INSERT INTO THEATER
VALUES(TH_SEQ.NEXTVAL, '대학로', 4, '1관', 1, 10, 10, to_date('16-07-29 15:00:00','YY-MM-DD HH24:MI:SS'))

INSERT INTO THEATER
VALUES(TH_SEQ.NEXTVAL, '신촌', 3, '1관', 1, 10, 10, to_date('16-07-29 10:00:00','YY-MM-DD HH24:MI:SS'))

INSERT INTO THEATER
VALUES(TH_SEQ.NEXTVAL, '강남', 1, '1관', 1, 10, 10, to_date('16-07-29 20:00:00','YY-MM-DD HH24:MI:SS'))

INSERT INTO THEATER
VALUES(TH_SEQ.NEXTVAL, '강남', 4, '1관', 1, 10, 10, to_date('20160729123000','YYYYMMDDHH24MISS'))
---------------------------------------------------------------------------
SELECT * FROM THEATER

update theater set th_totalseat=10, th_leftseat=7 where th_seq='11'

INSERT INTO THEATER
--VALUES(TH_SEQ.NEXTVAL, '명동', 1, '1관', 1, 10, 10, to_date('16-07-29 12:30:00','YY-MM-DD HH24:MI:SS'))
VALUES(TH_SEQ.NEXTVAL, '명동', 1, '1관', 1, 10, 10, to_date('16-07-29 12:30:00','YY-MM-DD HH24:MI:SS'))

INSERT INTO THEATER
--VALUES(TH_SEQ.NEXTVAL, '명동', 1, '1관', 2, 10, 10, to_date('16-07-29 3:00:00','YY-MM-DD HH24:MI:SS'))
VALUES(TH_SEQ.NEXTVAL, '명동', 1, '1관', 2, 10, 10, to_date('16-07-29 3:00:00','YY-MM-DD HH24:MI:SS'))

INSERT INTO THEATER
--VALUES(TH_SEQ.NEXTVAL, '명동', 2, '2관', 1, 10, 10, to_date('16-07-29 13:00:00','YY-MM-DD HH24:MI:SS'))
VALUES(TH_SEQ.NEXTVAL, '명동', 2, '2관', 1, 10, 10, to_date('16-07-29 13:00:00','YY-MM-DD HH24:MI:SS'))

INSERT INTO THEATER
--VALUES(TH_SEQ.NEXTVAL, '대학로', 4, '1관', 1, 10, 10, to_date('16-07-29 15:00:00','YY-MM-DD HH24:MI:SS'))
VALUES(TH_SEQ.NEXTVAL, '대학로', 4, '1관', 1, 10, 10, to_date('16-07-29 15:00:00','YY-MM-DD HH24:MI:SS'))

INSERT INTO THEATER
--VALUES(TH_SEQ.NEXTVAL, '신촌', 3, '1관', 1, 10, 10, to_date('16-07-29 10:00:00','YY-MM-DD HH24:MI:SS'))
VALUES(TH_SEQ.NEXTVAL, '신촌', 3, '1관', 1, 10, 10, to_date('16-07-29 10:00:00','YY-MM-DD HH24:MI:SS'))

INSERT INTO THEATER
--VALUES(TH_SEQ.NEXTVAL, '강남', 1, '1관', 1, 10, 10, to_date('16-07-29 20:00:00','YY-MM-DD HH24:MI:SS'))
VALUES(TH_SEQ.NEXTVAL, '강남', 1, '1관', 1, 10, 10, to_date('16-07-29 20:00:00','YY-MM-DD HH24:MI:SS'))

INSERT INTO THEATER
--VALUES(TH_SEQ.NEXTVAL, '독산', 5, '6관', 5, 10, 10, to_date('14-01-01 20:00:00','YY-MM-DD HH24:MI:SS'))
VALUES(TH_SEQ.NEXTVAL, '독산', 5, '6관', 5, 10, 10, to_date('14-01-01 20:00:00','YY-MM-DD HH24:MI:SS'))

INSERT INTO THEATER
--VALUES(TH_SEQ.NEXTVAL, '신촌', 4, '5관', 5, 10, 10, to_date('16-07-31  10:00:00','YY-MM-DD HH24:MI:SS'))
VALUES(TH_SEQ.NEXTVAL, '신촌', 4, '5관', 5, 10, 10, to_date('16-07-31 10:00:00','YY-MM-DD HH24:MI:SS'))

INSERT INTO THEATER
--VALUES(TH_SEQ.NEXTVAL, '대학로', 4, '1관', 1, 10, 10, to_date('16-08-15 15:00:00','YY-MM-DD HH24:MI:SS'))
VALUES(TH_SEQ.NEXTVAL, '대학로', 4, '1관', 1, 10, 10, to_date('16-08-15 15:00:00','YY-MM-DD HH24:MI:SS'))

INSERT INTO THEATER
--VALUES(TH_SEQ.NEXTVAL, '대학로', 4, '1관', 1, 10, 10, to_date('16-08-15 15:00:00','YY-MM-DD HH24:MI:SS'))
VALUES(TH_SEQ.NEXTVAL, '명동', 1, '1관', 1, 10, 10, to_date('16-08-15 15:00:00','YY-MM-DD HH24:MI:SS'))

--11
INSERT INTO THEATER
--VALUES(TH_SEQ.NEXTVAL, '명동', 2, '2관', 1, 10, 10, to_date('16-08-13 13:00:00','YY-MM-DD HH24:MI:SS'))
VALUES(TH_SEQ.NEXTVAL, '명동', 1, '2관', 1, 10, 10, to_date('16-08-13 13:00:00','YY-MM-DD HH24:MI:SS'))


--RESERVATION---------
DROP TABLE RESERVATION
CASCADE CONSTRAINT;

DROP SEQUENCE R_SEQ

SELECT * FROM RESERVATION

CREATE TABLE RESERVATION(
	R_SEQ NUMBER PRIMARY KEY,
	M_ID VARCHAR2(50) NOT NULL,
	TH_SEQ NUMBER NOT NULL,
	MV_SEQ NUMBER NOT NULL, 
	R_POLL NUMBER NOT NULL,
	R_TOTALPRICE NUMBER NOT NULL,
	R_ADULT NUMBER NOT NULL,
	R_STUDENT NUMBER NOT NULL,
	R_ELDER NUMBER NOT NULL,
	R_SEAT VARCHAR2(50) NOT NULL,
	R_TIME DATE NOT NULL,
	R_VIEWTIME DATE NOT NULL,
	R_THNAME VARCHAR2(100) NOT NULL,
	R_CINEMA VARCHAR2(500) NOT NULL
)

CREATE SEQUENCE R_SEQ
START WITH 1 INCREMENT BY 1

ALTER TABLE RESERVATION 
ADD CONSTRAINT FK_RESERVATION_M_ID FOREIGN KEY(M_ID)
REFERENCES MEMBER(M_ID);

ALTER TABLE RESERVATION 
ADD CONSTRAINT FK_RESERVATION_TH_SEQ FOREIGN KEY(TH_SEQ)
REFERENCES THEATER(TH_SEQ);

ALTER TABLE RESERVATION 
ADD CONSTRAINT FK_RESERVATION_MV_SEQ FOREIGN KEY(MV_SEQ)
REFERENCES MOVIE(MV_SEQ);


--ALTER TABLE RESERVATION 
--ADD CONSTRAINT FK_RESERVATION_PR_SEQ FOREIGN KEY(R_TOTALPRICE)
--REFERENCES PRICE(P_SEQ);

delete from RESERVATION

SELECT * FROM RESERVATION

update RESERVATION set r_poll=1 where r_seq=1;

--어바웃타임7 좋아요
INSERT INTO RESERVATION 
VALUES (R_SEQ.NEXTVAL, 'bombom', 7, 5, 1, 9000, 1,0,0,'S10',to_date('13-12-31 20:00:00','YY-MM-DD HH24:MI:SS'), to_date('14-01-01 20:00:00','YY-MM-DD HH24:MI:SS'), '독산', '6관');

--부산행1
INSERT INTO RESERVATION 
VALUES (R_SEQ.NEXTVAL, 'bombom', 1, 1, 0, 27000, 3,0,0,'S8 S9 S10',to_date('16-07-28 20:00:00','YY-MM-DD HH24:MI:SS'),to_date('16-07-29 20:00:00','YY-MM-DD HH24:MI:SS'), '명동','1관');

--도리를찾아서8 싫어요
INSERT INTO RESERVATION 
VALUES (R_SEQ.NEXTVAL, 'bombom', 8, 4, 2, 9000, 1,0,0,'S10',to_date('16-07-30 20:00:00','YY-MM-DD HH24:MI:SS'),to_date('16-07-31 20:00:00','YY-MM-DD HH24:MI:SS'), '신촌','5관');

--도리를찾아서8
INSERT INTO RESERVATION
VALUES (R_SEQ.NEXTVAL, 'bombom', 9, 4, 0, 9000, 1,0,0,'S8',to_date('16-08-14 15:00:00','YY-MM-DD HH24:MI:SS'),to_date('16-08-15 15:00:00','YY-MM-DD HH24:MI:SS'), '대학로','1관');

--부산행1

INSERT INTO RESERVATION
VALUES (R_SEQ.NEXTVAL, 'bombom', 10, 1, 0, 27000, 3,0,0,'S5,S6,S7',to_date('16-07-29 20:00:00','YY-MM-DD HH24:MI:SS'),to_date('16-08-15 20:00:00','YY-MM-DD HH24:MI:SS'), '명동','1관');

--부산행
INSERT INTO RESERVATION
VALUES (R_SEQ.NEXTVAL, 'bombom', 11, 1, 0, 27000, 3,0,0,'S5,S6,S7',to_date('16-08-11 20:00:00','YY-MM-DD HH24:MI:SS'),to_date('16-08-13 20:00:00','YY-MM-DD HH24:MI:SS'), '명동','2관');

--hong예매
INSERT INTO RESERVATION
VALUES (R_SEQ.NEXTVAL, 'hong', 9, 2, 0, 9000, 1,0,0,'S3',to_date('16-07-29 20:00:00','YY-MM-DD HH24:MI:SS'),to_date('16-08-22 20:00:00','YY-MM-DD HH24:MI:SS'), '대학로','1관');

DELETE FROM RESERVATION WHERE M_ID='bombom'
DELETE FROM MEMBER WHERE M_ID='bombom'

DELETE FROM MEMBER WHERE M_ID='bombom' 

--컬럼추가
ALTER TABLE RESERVATION ADD (R_TIME DATE )

SELECT * FROM RESERVATION WHERE R_TIME>SYSDATE
SELECT * FROM RESERVATION WHERE R_TIME<SYSDATE


--SEAT---------SEAT : 좌석 수 == COLUMN 수 
DROP TABLE SEAT
CASCADE CONSTRAINT;

DROP SEQUENCE S_SEQ; 

SELECT * FROM SEAT
 
CREATE TABLE SEAT(
	S_SEQ NUMBER PRIMARY KEY,
	TH_SEQ NUMBER NOT NULL,
	S_NAME VARCHAR2(50) NOT NULL,
	S_CHECK NUMBER(1)
)

CREATE SEQUENCE S_SEQ
START WITH 1 INCREMENT BY 1


ALTER TABLE SEAT 
ADD CONSTRAINT FK_SEAT_TH_SEQ FOREIGN KEY(TH_SEQ)
REFERENCES THEATER(TH_SEQ);

INSERT INTO SEAT VALUES (S_SEQ.NEXTVAL,1,'S10',0);
INSERT INTO SEAT VALUES (S_SEQ.NEXTVAL,1,'S9',0);
INSERT INTO SEAT VALUES (S_SEQ.NEXTVAL,1,'S8',0);

INSERT INTO SEAT VALUES (S_SEQ.NEXTVAL,7,'S10',0);

INSERT INTO SEAT VALUES (S_SEQ.NEXTVAL,8,'S10',0);

INSERT INTO SEAT VALUES (S_SEQ.NEXTVAL,9,'S1',0);INSERT INTO SEAT VALUES (S_SEQ.NEXTVAL,9,'S2',0);INSERT INTO SEAT VALUES (S_SEQ.NEXTVAL,9,'S3',0);INSERT INTO SEAT VALUES (S_SEQ.NEXTVAL,9,'S4',0);INSERT INTO SEAT VALUES (S_SEQ.NEXTVAL,9,'S5',0);INSERT INTO SEAT VALUES (S_SEQ.NEXTVAL,9,'S6',0);INSERT INTO SEAT VALUES (S_SEQ.NEXTVAL,9,'S7',0);INSERT INTO SEAT VALUES (S_SEQ.NEXTVAL,9,'S8',0);INSERT INTO SEAT VALUES (S_SEQ.NEXTVAL,9,'S9',0);INSERT INTO SEAT VALUES (S_SEQ.NEXTVAL,9,'S10',0);

INSERT INTO SEAT VALUES (S_SEQ.NEXTVAL,10,'S1',0);INSERT INTO SEAT VALUES (S_SEQ.NEXTVAL,10,'S2',0);INSERT INTO SEAT VALUES (S_SEQ.NEXTVAL,10,'S3',0);INSERT INTO SEAT VALUES (S_SEQ.NEXTVAL,10,'S4',0);INSERT INTO SEAT VALUES (S_SEQ.NEXTVAL,10,'S5',0);INSERT INTO SEAT VALUES (S_SEQ.NEXTVAL,10,'S6',0);INSERT INTO SEAT VALUES (S_SEQ.NEXTVAL,10,'S7',0);INSERT INTO SEAT VALUES (S_SEQ.NEXTVAL,10,'S8',0);INSERT INTO SEAT VALUES (S_SEQ.NEXTVAL,10,'S9',0);INSERT INTO SEAT VALUES (S_SEQ.NEXTVAL,10,'S10',0);

INSERT INTO SEAT VALUES (S_SEQ.NEXTVAL,11,'S1',0);
INSERT INTO SEAT VALUES (S_SEQ.NEXTVAL,11,'S2',0);
INSERT INTO SEAT VALUES (S_SEQ.NEXTVAL,11,'S3',0);
INSERT INTO SEAT VALUES (S_SEQ.NEXTVAL,11,'S4',0);
INSERT INTO SEAT VALUES (S_SEQ.NEXTVAL,11,'S5',0);
INSERT INTO SEAT VALUES (S_SEQ.NEXTVAL,11,'S6',0);
INSERT INTO SEAT VALUES (S_SEQ.NEXTVAL,11,'S7',0);
INSERT INTO SEAT VALUES (S_SEQ.NEXTVAL,11,'S8',0);
INSERT INTO SEAT VALUES (S_SEQ.NEXTVAL,11,'S9',0);
INSERT INTO SEAT VALUES (S_SEQ.NEXTVAL,11,'S10',0);

UPDATE SEAT SET S_CHECK='1' WHERE S_NAME='S5' AND S_SEQ=5; 
UPDATE SEAT SET S_CHECK='1' WHERE TH_SEQ=10 AND S_NAME='S5';
UPDATE SEAT SET S_CHECK='1' WHERE TH_SEQ=10 AND S_NAME='S6';
UPDATE SEAT SET S_CHECK='1' WHERE TH_SEQ=10 AND S_NAME='S7';
UPDATE SEAT SET S_CHECK='1' WHERE TH_SEQ=9 AND S_NAME='S8'; 
UPDATE SEAT SET S_CHECK='1' WHERE TH_SEQ=9 AND S_NAME='S3'; 
UPDATE SEAT SET S_CHECK='1' WHERE S_NAME='S10' AND TH_SEQ=8; 
UPDATE SEAT SET S_CHECK='1' WHERE S_NAME='S10' AND TH_SEQ=7; 

UPDATE SEAT SET S_CHECK='1' WHERE S_NAME='S10' AND TH_SEQ=1;
UPDATE SEAT SET S_CHECK='1' WHERE S_NAME='S9' AND TH_SEQ=1;
UPDATE SEAT SET S_CHECK='1' WHERE S_NAME='S8' AND TH_SEQ=1;

UPDATE SEAT SET S_CHECK=1  WHERE S_NAME='S7' AND TH_SEQ=11

UPDATE SEAT SET S_CHECK=1 WHERE S_NAME='S5' AND TH_SEQ=11;
UPDATE SEAT SET S_CHECK=1 WHERE S_NAME='S6' AND TH_SEQ=11;
UPDATE SEAT SET S_CHECK=1 WHERE S_NAME='S7' AND TH_SEQ=11;

SELECT * FROM SEAT
--PRICE---------PRICE : 영화가격표 // P_GRADE : ADULT, STUDENT, ELDER
DROP TABLE PRICE
CASCADE CONSTRAINT;

DROP SEQUENCE P_SEQ

SELECT * FROM PRICE

CREATE TABLE PRICE(
	P_SEQ NUMBER PRIMARY KEY,
	P_GRADE VARCHAR2(10) NOT NULL,
	P_PRICE NUMBER NOT NULL
)

CREATE SEQUENCE P_SEQ
START WITH 1 INCREMENT BY 1
/*
INSERT INTO PRICE VALUES(P_SEQ.NEXTVAL, 'adult', '10000')
INSERT INTO PRICE VALUES(P_SEQ.NEXTVAL, 'student', '8000')
INSERT INTO PRICE VALUES(P_SEQ.NEXTVAL, 'elder', '5000')
*/

INSERT INTO PRICE VALUES (P_SEQ.NEXTVAL, 'ADULT', 9000);
INSERT INTO PRICE VALUES (P_SEQ.NEXTVAL, 'STUDENT', 6000);
INSERT INTO PRICE VALUES (P_SEQ.NEXTVAL, 'ELDER', 4500);

SELECT * FROM SEAT

UPDATE SEAT SET S1=' ',S2=' ',S3=' ',S4=' ',S5=' ',S6=' ',S7=' ',S8=' ',S9=' ',S10=' '
WHERE S1||S2||S3||S4||S5||S6||S7||S8||S9||S10 LIKE 'S%' AND TH_SEQ='11'


UPDATE THEATER SET TH_TOTALSEAT=TH_TOTALSEAT+1,TH_LEFTSEAT=TH_LEFTSEAT-1 WHERE TH_SEQ=11